databases:
  - name: bs_DB
    databaseName: bs_db
    user: bistroselect
    region: singapore

services:
  - type: web
    name: bistroselect
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bistroselect
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false